 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/foodtruck/orders", type: :request do
  
  # Foodtruck::Order. As you add validations to Foodtruck::Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Foodtruck::Order.create! valid_attributes
      get foodtruck_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order = Foodtruck::Order.create! valid_attributes
      get foodtruck_order_url(foodtruck_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_foodtruck_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      order = Foodtruck::Order.create! valid_attributes
      get edit_foodtruck_order_url(foodtruck_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Foodtruck::Order" do
        expect {
          post foodtruck_orders_url, params: { foodtruck_order: valid_attributes }
        }.to change(Foodtruck::Order, :count).by(1)
      end

      it "redirects to the created foodtruck_order" do
        post foodtruck_orders_url, params: { foodtruck_order: valid_attributes }
        expect(response).to redirect_to(foodtruck_order_url(@foodtruck_order))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Foodtruck::Order" do
        expect {
          post foodtruck_orders_url, params: { foodtruck_order: invalid_attributes }
        }.to change(Foodtruck::Order, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post foodtruck_orders_url, params: { foodtruck_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested foodtruck_order" do
        order = Foodtruck::Order.create! valid_attributes
        patch foodtruck_order_url(foodtruck_order), params: { foodtruck_order: new_attributes }
        order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the foodtruck_order" do
        order = Foodtruck::Order.create! valid_attributes
        patch foodtruck_order_url(foodtruck_order), params: { foodtruck_order: new_attributes }
        order.reload
        expect(response).to redirect_to(foodtruck_order_url(order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        order = Foodtruck::Order.create! valid_attributes
        patch foodtruck_order_url(foodtruck_order), params: { foodtruck_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested foodtruck_order" do
      order = Foodtruck::Order.create! valid_attributes
      expect {
        delete foodtruck_order_url(foodtruck_order)
      }.to change(Foodtruck::Order, :count).by(-1)
    end

    it "redirects to the foodtruck_orders list" do
      order = Foodtruck::Order.create! valid_attributes
      delete foodtruck_order_url(foodtruck_order)
      expect(response).to redirect_to(foodtruck_orders_url)
    end
  end
end
